# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_call:

permissions:
  contents: read

jobs:
  test:
    strategy:
      matrix:
        module: [uitextcompose-core, uitextcompose-android, uitextcompose-multiplatform]
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          libgl1 \
          xvfb \
          libxtst6 \
          libxi6

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Enable KVM
      if: matrix.module == 'uitextcompose-android'
      run: |
        echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
        sudo udevadm control --reload-rules
        sudo udevadm trigger --name-match=kvm

    - name: Setup Android SDK
      if: matrix.module == 'uitextcompose-android'
      uses: android-actions/setup-android@v3
      with:
        log-accepted-android-sdk-licenses: false

    - name: Validate Gradle Wrapper
      uses: gradle/actions/wrapper-validation@v3

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3

    - name: Execute Core Check
      if: matrix.module == 'uitextcompose-core'
      run: ./gradlew uitextcompose-core:check

    - name: Execute Multiplatform Tests
      if: matrix.module == 'uitextcompose-multiplatform'
      run: xvfb-run ./gradlew uitextcompose-multiplatform:check uitextcompose-multiplatform:desktopTest

    - name: Execute Android Tests
      if: matrix.module == 'uitextcompose-android'
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 29
        target: google_apis
        arch: x86_64
        profile: Nexus 6
        script: xvfb-run ./gradlew uitextcompose-android:check uitextcompose-android:connectedAndroidTest